# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/slahmer/CLionProjects/Net_Traffic_Analyser

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/slahmer/CLionProjects/Net_Traffic_Analyser

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/slahmer/CLionProjects/Net_Traffic_Analyser/CMakeFiles /home/slahmer/CLionProjects/Net_Traffic_Analyser/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/slahmer/CLionProjects/Net_Traffic_Analyser/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

application_layer.o: application_layer.c.o

.PHONY : application_layer.o

# target to build an object file
application_layer.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/application_layer.c.o
.PHONY : application_layer.c.o

application_layer.i: application_layer.c.i

.PHONY : application_layer.i

# target to preprocess a source file
application_layer.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/application_layer.c.i
.PHONY : application_layer.c.i

application_layer.s: application_layer.c.s

.PHONY : application_layer.s

# target to generate assembly for a file
application_layer.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/application_layer.c.s
.PHONY : application_layer.c.s

internet_layer.o: internet_layer.c.o

.PHONY : internet_layer.o

# target to build an object file
internet_layer.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/internet_layer.c.o
.PHONY : internet_layer.c.o

internet_layer.i: internet_layer.c.i

.PHONY : internet_layer.i

# target to preprocess a source file
internet_layer.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/internet_layer.c.i
.PHONY : internet_layer.c.i

internet_layer.s: internet_layer.c.s

.PHONY : internet_layer.s

# target to generate assembly for a file
internet_layer.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/internet_layer.c.s
.PHONY : internet_layer.c.s

link_layer.o: link_layer.c.o

.PHONY : link_layer.o

# target to build an object file
link_layer.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/link_layer.c.o
.PHONY : link_layer.c.o

link_layer.i: link_layer.c.i

.PHONY : link_layer.i

# target to preprocess a source file
link_layer.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/link_layer.c.i
.PHONY : link_layer.c.i

link_layer.s: link_layer.c.s

.PHONY : link_layer.s

# target to generate assembly for a file
link_layer.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/link_layer.c.s
.PHONY : link_layer.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.s
.PHONY : main.c.s

transport_layer.o: transport_layer.c.o

.PHONY : transport_layer.o

# target to build an object file
transport_layer.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/transport_layer.c.o
.PHONY : transport_layer.c.o

transport_layer.i: transport_layer.c.i

.PHONY : transport_layer.i

# target to preprocess a source file
transport_layer.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/transport_layer.c.i
.PHONY : transport_layer.c.i

transport_layer.s: transport_layer.c.s

.PHONY : transport_layer.s

# target to generate assembly for a file
transport_layer.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/transport_layer.c.s
.PHONY : transport_layer.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... edit_cache"
	@echo "... application_layer.o"
	@echo "... application_layer.i"
	@echo "... application_layer.s"
	@echo "... internet_layer.o"
	@echo "... internet_layer.i"
	@echo "... internet_layer.s"
	@echo "... link_layer.o"
	@echo "... link_layer.i"
	@echo "... link_layer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... transport_layer.o"
	@echo "... transport_layer.i"
	@echo "... transport_layer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

